/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const StudentLazyImport = createFileRoute('/student')()
const RegisterLazyImport = createFileRoute('/register')()
const ProfileLazyImport = createFileRoute('/profile')()
const LoginLazyImport = createFileRoute('/login')()
const IndexLazyImport = createFileRoute('/')()
const StudentsCreateLazyImport = createFileRoute('/students/create')()
const StudentsIdLazyImport = createFileRoute('/students/$id')()
const ManufactureRefreshLazyImport = createFileRoute('/manufacture/refresh')()
const ManufactureCreateLazyImport = createFileRoute('/manufacture/create')()
const StudentsEditIdLazyImport = createFileRoute('/students/edit/$id')()
const ManufactureEditIdLazyImport = createFileRoute('/manufacture/edit/$id')()

// Create/Update Routes

const StudentLazyRoute = StudentLazyImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/student.lazy').then((d) => d.Route))

const RegisterLazyRoute = RegisterLazyImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/register.lazy').then((d) => d.Route))

const ProfileLazyRoute = ProfileLazyImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/profile.lazy').then((d) => d.Route))

const LoginLazyRoute = LoginLazyImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const StudentsCreateLazyRoute = StudentsCreateLazyImport.update({
  id: '/students/create',
  path: '/students/create',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/students/create.lazy').then((d) => d.Route),
)

const StudentsIdLazyRoute = StudentsIdLazyImport.update({
  id: '/students/$id',
  path: '/students/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/students/$id.lazy').then((d) => d.Route))

const ManufactureRefreshLazyRoute = ManufactureRefreshLazyImport.update({
  id: '/manufacture/refresh',
  path: '/manufacture/refresh',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/manufacture/refresh.lazy').then((d) => d.Route),
)

const ManufactureCreateLazyRoute = ManufactureCreateLazyImport.update({
  id: '/manufacture/create',
  path: '/manufacture/create',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/manufacture/create.lazy').then((d) => d.Route),
)

const StudentsEditIdLazyRoute = StudentsEditIdLazyImport.update({
  id: '/students/edit/$id',
  path: '/students/edit/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/students/edit/$id.lazy').then((d) => d.Route),
)

const ManufactureEditIdLazyRoute = ManufactureEditIdLazyImport.update({
  id: '/manufacture/edit/$id',
  path: '/manufacture/edit/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/manufacture/edit/$id.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileLazyImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterLazyImport
      parentRoute: typeof rootRoute
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentLazyImport
      parentRoute: typeof rootRoute
    }
    '/manufacture/create': {
      id: '/manufacture/create'
      path: '/manufacture/create'
      fullPath: '/manufacture/create'
      preLoaderRoute: typeof ManufactureCreateLazyImport
      parentRoute: typeof rootRoute
    }
    '/manufacture/refresh': {
      id: '/manufacture/refresh'
      path: '/manufacture/refresh'
      fullPath: '/manufacture/refresh'
      preLoaderRoute: typeof ManufactureRefreshLazyImport
      parentRoute: typeof rootRoute
    }
    '/students/$id': {
      id: '/students/$id'
      path: '/students/$id'
      fullPath: '/students/$id'
      preLoaderRoute: typeof StudentsIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/students/create': {
      id: '/students/create'
      path: '/students/create'
      fullPath: '/students/create'
      preLoaderRoute: typeof StudentsCreateLazyImport
      parentRoute: typeof rootRoute
    }
    '/manufacture/edit/$id': {
      id: '/manufacture/edit/$id'
      path: '/manufacture/edit/$id'
      fullPath: '/manufacture/edit/$id'
      preLoaderRoute: typeof ManufactureEditIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/students/edit/$id': {
      id: '/students/edit/$id'
      path: '/students/edit/$id'
      fullPath: '/students/edit/$id'
      preLoaderRoute: typeof StudentsEditIdLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/login': typeof LoginLazyRoute
  '/profile': typeof ProfileLazyRoute
  '/register': typeof RegisterLazyRoute
  '/student': typeof StudentLazyRoute
  '/manufacture/create': typeof ManufactureCreateLazyRoute
  '/manufacture/refresh': typeof ManufactureRefreshLazyRoute
  '/students/$id': typeof StudentsIdLazyRoute
  '/students/create': typeof StudentsCreateLazyRoute
  '/manufacture/edit/$id': typeof ManufactureEditIdLazyRoute
  '/students/edit/$id': typeof StudentsEditIdLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/login': typeof LoginLazyRoute
  '/profile': typeof ProfileLazyRoute
  '/register': typeof RegisterLazyRoute
  '/student': typeof StudentLazyRoute
  '/manufacture/create': typeof ManufactureCreateLazyRoute
  '/manufacture/refresh': typeof ManufactureRefreshLazyRoute
  '/students/$id': typeof StudentsIdLazyRoute
  '/students/create': typeof StudentsCreateLazyRoute
  '/manufacture/edit/$id': typeof ManufactureEditIdLazyRoute
  '/students/edit/$id': typeof StudentsEditIdLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/login': typeof LoginLazyRoute
  '/profile': typeof ProfileLazyRoute
  '/register': typeof RegisterLazyRoute
  '/student': typeof StudentLazyRoute
  '/manufacture/create': typeof ManufactureCreateLazyRoute
  '/manufacture/refresh': typeof ManufactureRefreshLazyRoute
  '/students/$id': typeof StudentsIdLazyRoute
  '/students/create': typeof StudentsCreateLazyRoute
  '/manufacture/edit/$id': typeof ManufactureEditIdLazyRoute
  '/students/edit/$id': typeof StudentsEditIdLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/profile'
    | '/register'
    | '/student'
    | '/manufacture/create'
    | '/manufacture/refresh'
    | '/students/$id'
    | '/students/create'
    | '/manufacture/edit/$id'
    | '/students/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/profile'
    | '/register'
    | '/student'
    | '/manufacture/create'
    | '/manufacture/refresh'
    | '/students/$id'
    | '/students/create'
    | '/manufacture/edit/$id'
    | '/students/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/profile'
    | '/register'
    | '/student'
    | '/manufacture/create'
    | '/manufacture/refresh'
    | '/students/$id'
    | '/students/create'
    | '/manufacture/edit/$id'
    | '/students/edit/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  LoginLazyRoute: typeof LoginLazyRoute
  ProfileLazyRoute: typeof ProfileLazyRoute
  RegisterLazyRoute: typeof RegisterLazyRoute
  StudentLazyRoute: typeof StudentLazyRoute
  ManufactureCreateLazyRoute: typeof ManufactureCreateLazyRoute
  ManufactureRefreshLazyRoute: typeof ManufactureRefreshLazyRoute
  StudentsIdLazyRoute: typeof StudentsIdLazyRoute
  StudentsCreateLazyRoute: typeof StudentsCreateLazyRoute
  ManufactureEditIdLazyRoute: typeof ManufactureEditIdLazyRoute
  StudentsEditIdLazyRoute: typeof StudentsEditIdLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  LoginLazyRoute: LoginLazyRoute,
  ProfileLazyRoute: ProfileLazyRoute,
  RegisterLazyRoute: RegisterLazyRoute,
  StudentLazyRoute: StudentLazyRoute,
  ManufactureCreateLazyRoute: ManufactureCreateLazyRoute,
  ManufactureRefreshLazyRoute: ManufactureRefreshLazyRoute,
  StudentsIdLazyRoute: StudentsIdLazyRoute,
  StudentsCreateLazyRoute: StudentsCreateLazyRoute,
  ManufactureEditIdLazyRoute: ManufactureEditIdLazyRoute,
  StudentsEditIdLazyRoute: StudentsEditIdLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/login",
        "/profile",
        "/register",
        "/student",
        "/manufacture/create",
        "/manufacture/refresh",
        "/students/$id",
        "/students/create",
        "/manufacture/edit/$id",
        "/students/edit/$id"
      ]
    },
    "/": {
      "filePath": "index.lazy.jsx"
    },
    "/login": {
      "filePath": "login.lazy.jsx"
    },
    "/profile": {
      "filePath": "profile.lazy.jsx"
    },
    "/register": {
      "filePath": "register.lazy.jsx"
    },
    "/student": {
      "filePath": "student.lazy.jsx"
    },
    "/manufacture/create": {
      "filePath": "manufacture/create.lazy.jsx"
    },
    "/manufacture/refresh": {
      "filePath": "manufacture/refresh.lazy.jsx"
    },
    "/students/$id": {
      "filePath": "students/$id.lazy.jsx"
    },
    "/students/create": {
      "filePath": "students/create.lazy.jsx"
    },
    "/manufacture/edit/$id": {
      "filePath": "manufacture/edit/$id.lazy.jsx"
    },
    "/students/edit/$id": {
      "filePath": "students/edit/$id.lazy.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
